spring.application.name=HomeChefPlatform
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.datasource.url=jdbc:mysql://localhost:3306/private_kitchen?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

aliyun.oss.bucket-name=wq-example-bucket
aliyun.oss.endpoint=oss-rg-china-mainland.aliyuncs.com
aliyun.oss.region=rg-china-mainland
aliyun.oss.access-key-id=LTAI5tPfgSe1h4hP7m5NvgM7
aliyun.oss.access-key-secret=xh5ZkTOFz6VN7hqKG7diVYkhiTYTkI
aliyun.oss.upload-prefix=avatars/
aliyun.oss.allowed-types=jpg,jpeg,png,webp
aliyun.oss.max-size-mb=5
aliyun.oss.custom-domain=

wechat.mini-program.app-id=wx6f566db36e447bd8
wechat.mini-program.app-secret=03835991693c3d0c5ccb18d57c7c1470

bailian.api-key=sk-4600674716b7498093a08a204565b5e1
bailian.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
bailian.model=qwen-plus

tencent.map.enabled=true
tencent.map.key=HYKBZ-UPUCM-HJX6V-6V7I3-577BT-B7BZD
tencent.map.base-url=https://apis.map.qq.com
tencent.map.distance-matrix-path=/ws/distance/v1/matrix
tencent.map.mode=driving
tencent.map.connect-timeout-ms=2000
tencent.map.read-timeout-ms=3000
